"""Environment-driven configuration.

A single `Settings` model is the source of truth. Defaults are chosen so
the server runs zero-config on a fresh checkout. Any env var below is
optional.

Env vars:
    CONTEXT_RETRIEVAL_DB    Path to the SQLite database. Default: ./data/context.db
    ANTHROPIC_API_KEY       If set, summaries are generated by Claude.
    ANTHROPIC_MODEL         Claude model id. Default: claude-sonnet-4-5
    EMBEDDING_MODEL         sentence-transformers model id. Default: sentence-transformers/all-MiniLM-L6-v2
    LOG_LEVEL               Python log level name. Default: INFO
    MAX_LOOKBACK            Upper bound on `set_lookback`. Default: 1000
    MAX_BLOCKS_TO_SUMMARIZE Cap on blocks sent to Claude in one summarize call. Default: 200
    MAX_CHARS_PER_BLOCK     Truncate any single block before summarization. Default: 1200
    SUMMARY_CACHE_TTL_SEC   Reuse the latest summary if it's at least this fresh. Default: 0 (cache only by block_count)
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


def _env(name: str, default: str | None = None) -> str | None:
    val = os.environ.get(name)
    if val is None or val == "":
        return default
    return val


def _env_int(name: str, default: int) -> int:
    raw = _env(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _default_db_path() -> Path:
    # Repo-relative: src/context_retrieval/config.py -> repo root is parents[2]
    return Path(__file__).resolve().parents[2] / "data" / "context.db"


class Settings(BaseModel):
    """All runtime configuration in one place."""

    model_config = ConfigDict(extra="ignore")

    db_path: Path = Field(default_factory=_default_db_path)
    anthropic_api_key: str | None = None
    anthropic_model: str = "claude-sonnet-4-5"
    embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    log_level: str = "INFO"
    max_lookback: int = Field(default=1000, ge=1)
    max_blocks_to_summarize: int = Field(default=200, ge=1)
    max_chars_per_block: int = Field(default=1200, ge=100)
    summary_cache_ttl_sec: int = Field(default=0, ge=0)

    @classmethod
    def from_env(cls) -> "Settings":
        db_override = _env("CONTEXT_RETRIEVAL_DB")
        kwargs: dict[str, Any] = {
            "anthropic_api_key": _env("ANTHROPIC_API_KEY"),
            "anthropic_model": _env("ANTHROPIC_MODEL", "claude-sonnet-4-5"),
            "embedding_model": _env(
                "EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2"
            ),
            "log_level": _env("LOG_LEVEL", "INFO"),
            "max_lookback": _env_int("MAX_LOOKBACK", 1000),
            "max_blocks_to_summarize": _env_int("MAX_BLOCKS_TO_SUMMARIZE", 200),
            "max_chars_per_block": _env_int("MAX_CHARS_PER_BLOCK", 1200),
            "summary_cache_ttl_sec": _env_int("SUMMARY_CACHE_TTL_SEC", 0),
        }
        if db_override:
            kwargs["db_path"] = Path(db_override).expanduser()
        return cls(**kwargs)

    @property
    def claude_enabled(self) -> bool:
        return bool(self.anthropic_api_key)
